name: Azure Static Web Apps â€” Deploy Supplications Folder

on:
  push:
    branches: [ AzkaarSalah ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Supplication After Prayers
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "Supplication After Prayers"
          api_location: ""
          app_build_command: 'echo "No build"'
          output_location: "."
